name: Azure Bicep Infra

on: [push, workflow_dispatch]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Lint Bicep code 


      # Deploy Bicep file to Development environment
    - name: Deploy to Dev
      if: github.ref == 'refs/heads/dev'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
        resourceGroupName: jseijas_students_1
        template: ./main.bicep
        parameters: dev.parameters.json dbuser=${{ secrets.DBUSER }} dbhost=${{ secrets.DBHOST }} dbpass=${{ secrets.DBPASS }} dbname=${{ secrets.DBNAME }}
        failOnStdErr: false

      # Deploy Bicep file to Production environment
    - name: Deploy to Prod
      if: github.ref == 'refs/heads/main'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
        resourceGroupName: jseijas_students_1
        template: ./main.bicep
        parameters: prod.parameters.json dbuser=${{ secrets.DBUSER }} dbhost=${{ secrets.DBHOST }} dbpass=${{ secrets.DBPASS }} dbname=${{ secrets.DBNAME }}
        failOnStdErr: false